project:
  type: website

website:
  title: "OptBlog"
  navbar:
    left:
      - about.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/MPF-Optimization-Laboratory/opt-blog/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/MPF-Optimization-Laboratory/opt-blog/discussions"
    tools:
      - icon: github
        href: https://github.com/MPF-Optimization-Laboratory/opt-blog
        text: OptBlog GitHub
  repo-url: https://github.com/MPF-Optimization-Laboratory/opt-blog/
  repo-actions: [edit, issue]
format:
  html:
    include-in-header:
      - text: |
          <meta name="robots" content="noindex">
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



